/* Generated by scripts/build-content.mjs. Do not edit by hand. */
import type { FieldNote, ImpactFact, ProfileSummary, Program, Project } from './types';

export const profile: ProfileSummary = {
  "username": "kaflah.organisation",
  "fullName": "Kaflah",
  "biography": "Towards Humanity",
  "externalUrl": "https://linktr.ee/kaflahorganisation",
  "followers": 359
};

export const programs: Program[] = [
  {
    "id": "sabzkal",
    "name": "SABZKAL",
    "shortLabel": "Environment",
    "color": "#3f6b39",
    "summary": "Plantation drives that turn youth energy toward greener school and university spaces.",
    "action": "Explore SabzKal"
  },
  {
    "id": "qalam",
    "name": "QALAM",
    "shortLabel": "Education",
    "color": "#214c9a",
    "summary": "Learning through supplies, libraries, creative activities, and practical school experiences.",
    "action": "Explore Qalam"
  },
  {
    "id": "khidmat-e-khalaq",
    "name": "KHIDMAT-E-KHALAQ",
    "shortLabel": "Community care",
    "color": "#8a3d4c",
    "summary": "Hands-on community care through health, Ramadan service, and fundraising activity.",
    "action": "Explore Khidmat-e-Khalaq"
  }
];
export const projects: Project[] = [
  {
    "slug": "east-stars-stationery-drive",
    "title": "East Stars Stationery Drive",
    "programId": "qalam",
    "dateLabel": "7 Mar 2024",
    "locationLabel": "East Stars School",
    "summary": "Stationery kits were shared with students alongside a simple reminder of why education matters.",
    "media": [
      "/media/2024-03-25_08-05-04_UTC_1.jpg",
      "/media/2024-03-25_08-05-04_UTC_1.mp4",
      "/media/2024-03-25_08-05-04_UTC_2.jpg",
      "/media/2024-03-25_08-05-04_UTC_2.mp4",
      "/media/2024-03-25_08-05-04_UTC_3.jpg",
      "/media/2024-03-25_08-05-04_UTC_3.mp4"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "C47gxOst2vX",
        "sourceUrl": "https://www.instagram.com/p/C47gxOst2vX/",
        "sourcePublishedAt": "2024-03-25T08:05:04+00:00"
      }
    ]
  },
  {
    "slug": "lahore-public-school-plantation-drive",
    "title": "Lahore Public School Plantation Drive",
    "programId": "sabzkal",
    "dateLabel": "13 Aug 2025",
    "locationLabel": "Lahore Public School",
    "summary": "Team Kaflah brought volunteers together to plant for a greener Pakistan.",
    "media": [
      "/media/2025-08-14_13-02-45_UTC_1.webp",
      "/media/2025-08-14_13-02-45_UTC_2.webp",
      "/media/2025-08-14_13-02-45_UTC_3.webp",
      "/media/2025-08-14_13-02-45_UTC_4.webp",
      "/media/2025-08-14_13-02-45_UTC_5.webp",
      "/media/2025-08-14_13-02-45_UTC_6.webp"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DNVh3CesWJB",
        "sourceUrl": "https://www.instagram.com/p/DNVh3CesWJB/",
        "sourcePublishedAt": "2025-08-14T13:02:45+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DNViPFqM55t",
        "sourceUrl": "https://www.instagram.com/p/DNViPFqM55t/",
        "sourcePublishedAt": "2025-08-14T13:07:46+00:00"
      }
    ]
  },
  {
    "slug": "kafalat-ghar-dental-camp",
    "title": "Kafalat Ghar Dental Camp",
    "programId": "khidmat-e-khalaq",
    "dateLabel": "18 Oct 2025",
    "locationLabel": "Kafalat Ghar Orphanage",
    "summary": "Children received dental check-ups, oral hygiene guidance, and dental kits through a volunteer-led camp.",
    "media": [
      "/media/2025-10-26_12-09-08_UTC_1.jpg",
      "/media/2025-10-26_12-09-08_UTC_2.jpg",
      "/media/2025-10-26_12-09-08_UTC_3.jpg",
      "/media/2025-10-26_12-09-08_UTC_4.jpg",
      "/media/2025-10-26_12-09-08_UTC_5.jpg",
      "/media/2025-10-26_12-09-08_UTC_6.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DQRZwOiEpbc",
        "sourceUrl": "https://www.instagram.com/p/DQRZwOiEpbc/",
        "sourcePublishedAt": "2025-10-26T12:09:08+00:00"
      }
    ]
  },
  {
    "slug": "gcu-plantation-drive",
    "title": "GCU Plantation Drive",
    "programId": "sabzkal",
    "dateLabel": "18 Nov 2025",
    "locationLabel": "GCU",
    "summary": "The Women Development Center, Kaflah, and Alkhidmat joined forces for a cleaner, greener Pakistan.",
    "media": [
      "/media/2025-11-18_20-00-24_UTC.jpg",
      "/media/2025-11-18_20-00-24_UTC.mp4"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DRNd5d0DHwL",
        "sourceUrl": "https://www.instagram.com/p/DRNd5d0DHwL/",
        "sourcePublishedAt": "2025-11-18T20:00:24+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DRRwVmXDKKS",
        "sourceUrl": "https://www.instagram.com/p/DRRwVmXDKKS/",
        "sourcePublishedAt": "2025-11-20T11:57:52+00:00"
      }
    ]
  },
  {
    "slug": "kafalat-ghar-stationery-drive",
    "title": "Kafalat Ghar Stationery Drive",
    "programId": "qalam",
    "dateLabel": "8 Jan 2026",
    "locationLabel": "Kafalat Ghar Orphanage",
    "summary": "Everyday stationery, colours, and colouring books gave children more room to imagine and create.",
    "media": [
      "/media/2026-01-12_10-19-29_UTC_1.jpg",
      "/media/2026-01-12_10-19-29_UTC_2.jpg",
      "/media/2026-01-12_10-19-29_UTC_3.jpg",
      "/media/2026-01-12_10-19-29_UTC_4.jpg",
      "/media/2026-01-12_10-19-29_UTC_5.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DTaDNewDMSy",
        "sourceUrl": "https://www.instagram.com/p/DTaDNewDMSy/",
        "sourcePublishedAt": "2026-01-12T10:19:29+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DTaxPOojFSg",
        "sourceUrl": "https://www.instagram.com/p/DTaxPOojFSg/",
        "sourcePublishedAt": "2026-01-12T17:02:04+00:00"
      }
    ]
  },
  {
    "slug": "alif-laila-library-reading-day",
    "title": "Alif Laila Library Reading Day",
    "programId": "qalam",
    "dateLabel": "28 Jan 2026",
    "locationLabel": "Alif Laila Library",
    "summary": "Project Zavia and Kaflah used reading, drawing, and donated books to make learning feel alive.",
    "media": [
      "/media/2026-01-31_11-56-11_UTC.jpg",
      "/media/2026-01-31_11-56-11_UTC.mp4"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DULJRR-CLrj",
        "sourceUrl": "https://www.instagram.com/p/DULJRR-CLrj/",
        "sourcePublishedAt": "2026-01-31T11:56:11+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DUOToorDBum",
        "sourceUrl": "https://www.instagram.com/p/DUOToorDBum/",
        "sourcePublishedAt": "2026-02-01T17:23:31+00:00"
      }
    ]
  },
  {
    "slug": "iftar-dastarkhuwan",
    "title": "Iftar Dastarkhuwan",
    "programId": "khidmat-e-khalaq",
    "dateLabel": "3 Mar 2026",
    "locationLabel": "Johan Town",
    "summary": "A Ramadan service initiative brought people together around a shared meal and a practical act of care.",
    "verifiedFacts": [
      "2,000+ people served"
    ],
    "media": [
      "/media/2026-03-04_16-48-57_UTC.jpg",
      "/media/2026-03-04_16-48-57_UTC.mp4"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DVeELm-DCw2",
        "sourceUrl": "https://www.instagram.com/p/DVeELm-DCw2/",
        "sourcePublishedAt": "2026-03-04T16:48:57+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DVgxyuaDG8c",
        "sourceUrl": "https://www.instagram.com/p/DVgxyuaDG8c/",
        "sourcePublishedAt": "2026-03-05T18:06:11+00:00"
      }
    ]
  },
  {
    "slug": "summer-internship",
    "title": "Summer Internship",
    "programId": "qalam",
    "dateLabel": "29 Jun – 2 Jul 2026",
    "locationLabel": "Government Girls Primary School Gulberg",
    "summary": "Young interns built an energetic learning environment through academic sessions, games, self-defence, and sports.",
    "media": [
      "/media/2026-06-29_11-24-54_UTC.jpg",
      "/media/2026-06-29_11-24-54_UTC.mp4"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DZ0LJy5sBuq",
        "sourceUrl": "https://www.instagram.com/p/DZ0LJy5sBuq/",
        "sourcePublishedAt": "2026-06-20T17:04:43+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaKwAJPwdEJ",
        "sourceUrl": "https://www.instagram.com/p/DaKwAJPwdEJ/",
        "sourcePublishedAt": "2026-06-29T11:24:54+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaPqP3HIBVP",
        "sourceUrl": "https://www.instagram.com/p/DaPqP3HIBVP/",
        "sourcePublishedAt": "2026-07-01T09:18:18+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaSvFUKsJKr",
        "sourceUrl": "https://www.instagram.com/p/DaSvFUKsJKr/",
        "sourcePublishedAt": "2026-07-02T13:54:29+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaVg9ZBsARX",
        "sourceUrl": "https://www.instagram.com/p/DaVg9ZBsARX/",
        "sourcePublishedAt": "2026-07-03T15:47:01+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaYXSzDsxTI",
        "sourceUrl": "https://www.instagram.com/p/DaYXSzDsxTI/",
        "sourcePublishedAt": "2026-07-04T18:18:13+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DakzaN-MyKb",
        "sourceUrl": "https://www.instagram.com/p/DakzaN-MyKb/",
        "sourcePublishedAt": "2026-07-09T14:18:16+00:00"
      }
    ]
  },
  {
    "slug": "project-zavia-fundraiser",
    "title": "Project Zavia Fundraiser",
    "programId": "khidmat-e-khalaq",
    "dateLabel": "30 Jul 2026",
    "locationLabel": "Pink Pistachio Cafe, Gulberg",
    "summary": "Project Zavia and Kaflah turned an evening of games and community into support for social causes.",
    "media": [
      "/media/2026-08-02_12-45-58_UTC_1.jpg",
      "/media/2026-08-02_12-45-58_UTC_2.jpg",
      "/media/2026-08-02_12-45-58_UTC_3.jpg",
      "/media/2026-08-02_12-45-58_UTC_4.jpg",
      "/media/2026-08-02_12-45-58_UTC_5.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbSwZC7I10L",
        "sourceUrl": "https://www.instagram.com/p/DbSwZC7I10L/",
        "sourcePublishedAt": "2026-07-27T10:41:03+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbfrFigosvk",
        "sourceUrl": "https://www.instagram.com/p/DbfrFigosvk/",
        "sourcePublishedAt": "2026-08-01T11:00:50+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbicjDXjMQ_",
        "sourceUrl": "https://www.instagram.com/p/DbicjDXjMQ_/",
        "sourcePublishedAt": "2026-08-02T12:45:58+00:00"
      }
    ]
  }
];
export const fieldNotes: FieldNote[] = [
  {
    "slug": "east-stars-stationery-drive",
    "title": "East Stars Stationery Drive",
    "dateLabel": "7 Mar 2024",
    "locationLabel": "East Stars School",
    "programId": "qalam",
    "summary": "Stationery kits were shared with students alongside a simple reminder of why education matters.",
    "media": [
      "/media/2024-03-25_08-05-04_UTC_1.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "C47gxOst2vX",
        "sourceUrl": "https://www.instagram.com/p/C47gxOst2vX/",
        "sourcePublishedAt": "2024-03-25T08:05:04+00:00"
      }
    ]
  },
  {
    "slug": "lahore-public-school-plantation-drive",
    "title": "Lahore Public School Plantation Drive",
    "dateLabel": "13 Aug 2025",
    "locationLabel": "Lahore Public School",
    "programId": "sabzkal",
    "summary": "Team Kaflah brought volunteers together to plant for a greener Pakistan.",
    "media": [
      "/media/2025-08-14_13-02-45_UTC_1.webp"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DNVh3CesWJB",
        "sourceUrl": "https://www.instagram.com/p/DNVh3CesWJB/",
        "sourcePublishedAt": "2025-08-14T13:02:45+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DNViPFqM55t",
        "sourceUrl": "https://www.instagram.com/p/DNViPFqM55t/",
        "sourcePublishedAt": "2025-08-14T13:07:46+00:00"
      }
    ]
  },
  {
    "slug": "kafalat-ghar-dental-camp",
    "title": "Kafalat Ghar Dental Camp",
    "dateLabel": "18 Oct 2025",
    "locationLabel": "Kafalat Ghar Orphanage",
    "programId": "khidmat-e-khalaq",
    "summary": "Children received dental check-ups, oral hygiene guidance, and dental kits through a volunteer-led camp.",
    "media": [
      "/media/2025-10-26_12-09-08_UTC_1.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DQRZwOiEpbc",
        "sourceUrl": "https://www.instagram.com/p/DQRZwOiEpbc/",
        "sourcePublishedAt": "2025-10-26T12:09:08+00:00"
      }
    ]
  },
  {
    "slug": "gcu-plantation-drive",
    "title": "GCU Plantation Drive",
    "dateLabel": "18 Nov 2025",
    "locationLabel": "GCU",
    "programId": "sabzkal",
    "summary": "The Women Development Center, Kaflah, and Alkhidmat joined forces for a cleaner, greener Pakistan.",
    "media": [
      "/media/2025-11-18_20-00-24_UTC.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DRNd5d0DHwL",
        "sourceUrl": "https://www.instagram.com/p/DRNd5d0DHwL/",
        "sourcePublishedAt": "2025-11-18T20:00:24+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DRRwVmXDKKS",
        "sourceUrl": "https://www.instagram.com/p/DRRwVmXDKKS/",
        "sourcePublishedAt": "2025-11-20T11:57:52+00:00"
      }
    ]
  },
  {
    "slug": "kafalat-ghar-stationery-drive",
    "title": "Kafalat Ghar Stationery Drive",
    "dateLabel": "8 Jan 2026",
    "locationLabel": "Kafalat Ghar Orphanage",
    "programId": "qalam",
    "summary": "Everyday stationery, colours, and colouring books gave children more room to imagine and create.",
    "media": [
      "/media/2026-01-12_10-19-29_UTC_1.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DTaDNewDMSy",
        "sourceUrl": "https://www.instagram.com/p/DTaDNewDMSy/",
        "sourcePublishedAt": "2026-01-12T10:19:29+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DTaxPOojFSg",
        "sourceUrl": "https://www.instagram.com/p/DTaxPOojFSg/",
        "sourcePublishedAt": "2026-01-12T17:02:04+00:00"
      }
    ]
  },
  {
    "slug": "alif-laila-library-reading-day",
    "title": "Alif Laila Library Reading Day",
    "dateLabel": "28 Jan 2026",
    "locationLabel": "Alif Laila Library",
    "programId": "qalam",
    "summary": "Project Zavia and Kaflah used reading, drawing, and donated books to make learning feel alive.",
    "media": [
      "/media/2026-01-31_11-56-11_UTC.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DULJRR-CLrj",
        "sourceUrl": "https://www.instagram.com/p/DULJRR-CLrj/",
        "sourcePublishedAt": "2026-01-31T11:56:11+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DUOToorDBum",
        "sourceUrl": "https://www.instagram.com/p/DUOToorDBum/",
        "sourcePublishedAt": "2026-02-01T17:23:31+00:00"
      }
    ]
  },
  {
    "slug": "iftar-dastarkhuwan",
    "title": "Iftar Dastarkhuwan",
    "dateLabel": "3 Mar 2026",
    "locationLabel": "Johan Town",
    "programId": "khidmat-e-khalaq",
    "summary": "A Ramadan service initiative brought people together around a shared meal and a practical act of care.",
    "media": [
      "/media/2026-03-04_16-48-57_UTC.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DVeELm-DCw2",
        "sourceUrl": "https://www.instagram.com/p/DVeELm-DCw2/",
        "sourcePublishedAt": "2026-03-04T16:48:57+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DVgxyuaDG8c",
        "sourceUrl": "https://www.instagram.com/p/DVgxyuaDG8c/",
        "sourcePublishedAt": "2026-03-05T18:06:11+00:00"
      }
    ]
  },
  {
    "slug": "summer-internship",
    "title": "Summer Internship",
    "dateLabel": "29 Jun – 2 Jul 2026",
    "locationLabel": "Government Girls Primary School Gulberg",
    "programId": "qalam",
    "summary": "Young interns built an energetic learning environment through academic sessions, games, self-defence, and sports.",
    "media": [
      "/media/2026-06-29_11-24-54_UTC.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DZ0LJy5sBuq",
        "sourceUrl": "https://www.instagram.com/p/DZ0LJy5sBuq/",
        "sourcePublishedAt": "2026-06-20T17:04:43+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaKwAJPwdEJ",
        "sourceUrl": "https://www.instagram.com/p/DaKwAJPwdEJ/",
        "sourcePublishedAt": "2026-06-29T11:24:54+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaPqP3HIBVP",
        "sourceUrl": "https://www.instagram.com/p/DaPqP3HIBVP/",
        "sourcePublishedAt": "2026-07-01T09:18:18+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaSvFUKsJKr",
        "sourceUrl": "https://www.instagram.com/p/DaSvFUKsJKr/",
        "sourcePublishedAt": "2026-07-02T13:54:29+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaVg9ZBsARX",
        "sourceUrl": "https://www.instagram.com/p/DaVg9ZBsARX/",
        "sourcePublishedAt": "2026-07-03T15:47:01+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DaYXSzDsxTI",
        "sourceUrl": "https://www.instagram.com/p/DaYXSzDsxTI/",
        "sourcePublishedAt": "2026-07-04T18:18:13+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DakzaN-MyKb",
        "sourceUrl": "https://www.instagram.com/p/DakzaN-MyKb/",
        "sourcePublishedAt": "2026-07-09T14:18:16+00:00"
      }
    ]
  },
  {
    "slug": "project-zavia-fundraiser",
    "title": "Project Zavia Fundraiser",
    "dateLabel": "30 Jul 2026",
    "locationLabel": "Pink Pistachio Cafe, Gulberg",
    "programId": "khidmat-e-khalaq",
    "summary": "Project Zavia and Kaflah turned an evening of games and community into support for social causes.",
    "media": [
      "/media/2026-08-02_12-45-58_UTC_1.jpg"
    ],
    "sourcePosts": [
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbSwZC7I10L",
        "sourceUrl": "https://www.instagram.com/p/DbSwZC7I10L/",
        "sourcePublishedAt": "2026-07-27T10:41:03+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbfrFigosvk",
        "sourceUrl": "https://www.instagram.com/p/DbfrFigosvk/",
        "sourcePublishedAt": "2026-08-01T11:00:50+00:00"
      },
      {
        "sourcePlatform": "instagram",
        "sourcePostId": "DbicjDXjMQ_",
        "sourceUrl": "https://www.instagram.com/p/DbicjDXjMQ_/",
        "sourcePublishedAt": "2026-08-02T12:45:58+00:00"
      }
    ]
  }
];
export const impactFacts: ImpactFact[] = [{
  "value": "2,000+",
  "label": "people served at the Iftar Dastarkhuwan",
  "source": {
    "sourcePlatform": "instagram",
    "sourcePostId": "DVeELm-DCw2",
    "sourceUrl": "https://www.instagram.com/p/DVeELm-DCw2/",
    "sourcePublishedAt": "2026-03-04T16:48:57+00:00"
  }
}];
export const heroMedia = [
  '/media/2026-03-04_16-48-57_UTC.jpg',
  '/media/2025-08-14_13-02-45_UTC_1.webp',
  '/media/2026-01-31_11-56-11_UTC.jpg'
];
